config/routes.rb
Rails.application.routes.draw do
  resources :logs, only: [:index]
  resources :comentarios
  resources :elencos
  resources :atores
  resources :filmes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "filmes#index"
end

app/models/comentario.rb
class Comentario < ApplicationRecord

  scope :aprovados, -> { where(aprovado: true) }
  scope :naoAprovados, -> { where(aprovado: false) }

  belongs_to :filme

  validates :conteudo, :filme_id, presence: true
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: %i[ show edit update destroy ]
  after_action :set_log, only: %i[ create update ]

  # GET /comentarios or /comentarios.json
  def index
    @comentarios = Comentario.naoAprovados
  end

  # GET /comentarios/1 or /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios or /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to comentarios_path, notice: "Comentario was successfully created." }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1 or /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to comentarios_path, notice: "Comentario was successfully updated." }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1 or /comentarios/1.json
  def destroy
    @comentario.destroy

    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: "Comentario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    def set_log
      if @comentario.aprovado
        @log = Log.new
        @log.comentario = @comentario
        @log.save
      end
    end

    # Only allow a list of trusted parameters through.
    def comentario_params
      params.require(:comentario).permit(:conteudo, :filme_id, :aprovado)
    end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_comentario.html.erb
<div id="<%= dom_id comentario %>">
  <p>
    <strong>Conteudo:</strong>
    <%= comentario.conteudo %>
  </p>

  <p>
    <strong>Filme:</strong>
    <%= comentario.filme_id %>
  </p>

  <p>
    <strong>Aprovado:</strong>
    <%= comentario.aprovado %>
  </p>

</div>

app/views/comentarios/_form.html.erb
<%= form_with(model: comentario) do |form| %>
  <% if comentario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
        <% comentario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div>
      <%= form.label :filme_id, "Escolha um filme" %>
    </div>
    <%= form.collection_select :filme_id, Filme.order(:nome), :id, :titulo %>
  </div>

  <br>

  <div>
    <%= form.label :conteudo,"Escreva seu comentário", style: "display: block"%>
    <%= form.text_area :conteudo, size: "100x10" %>
  </div>

  <br>

  <div>
    <%= form.label :aprovado, style: "display: block" %>
    <%= form.check_box :aprovado %>
  </div>
  
  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render "form", comentario: @comentario %>

<br>

<div>
  <%= link_to "Detalhes do comentário", @comentario %> 
  <%= link_to "listar comentarios", comentarios_path %>
</div>

app/views/comentarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comentarios</h1>

<div id="comentarios">
  <hr>
  <% @comentarios.each do |comentario| %>
    <%= render comentario %>
    <p>
      <%= link_to "Detalhes do Comentário", comentario %>
    </p>
    <hr>
  <% end %>
</div>

<%= link_to "Novo Comentário", new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>Novo Comentário</h1>

<%= render "form", comentario: @comentario %>

<br>

<div>
  <%= link_to "Listar Comentários", comentarios_path %>
</div>

app/views/comentarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comentario %>

<div>
  <%= link_to "Editar Comentário", edit_comentario_path(@comentario) %> |
  <%= link_to "Listar Comentários", comentarios_path %>

  <br>
  <br>
  <%= button_to "Apagar Comentário", @comentario, method: :delete %>
</div>