config/routes.rb
Rails.application.routes.draw do
  resources :logs, only: [:index]
  resources :comentarios
  resources :elencos
  resources :atores
  resources :filmes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "filmes#index"
end

app/models/atore.rb
class Atore < ApplicationRecord
    has_many :elencos
    has_many :filmes, through: :elencos

    validates :nome, :ano_nascimento, :emaisl, presence: true
    validates :emaisl, uniqueness: true
end

app/controllers/atores_controller.rb
class AtoresController < ApplicationController
  before_action :set_atore, only: %i[ show edit update destroy ]

  # GET /atores or /atores.json
  def index
    @atores = Atore.all
  end

  # GET /atores/1 or /atores/1.json
  def show
  end

  # GET /atores/new
  def new
    @atore = Atore.new
  end

  # GET /atores/1/edit
  def edit
  end

  # POST /atores or /atores.json
  def create
    @atore = Atore.new(atore_params)

    respond_to do |format|
      if @atore.save
        format.html { redirect_to atore_url(@atore), notice: "Atore was successfully created." }
        format.json { render :show, status: :created, location: @atore }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @atore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atores/1 or /atores/1.json
  def update
    respond_to do |format|
      if @atore.update(atore_params)
        format.html { redirect_to atore_url(@atore), notice: "Atore was successfully updated." }
        format.json { render :show, status: :ok, location: @atore }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @atore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atores/1 or /atores/1.json
  def destroy
    @atore.destroy

    respond_to do |format|
      format.html { redirect_to atores_url, notice: "Atore was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atore
      @atore = Atore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def atore_params
      params.require(:atore).permit(:nome, :ano_nascimento, :emaisl)
    end
end

app/helpers/atores_helper.rb
module AtoresHelper
end

app/views/atores/_atore.html.erb
<div id="<%= dom_id atore %>">
  <p>
    <strong>Nome:</strong>
    <%= atore.nome %>
  </p>

  <p>
    <strong>Ano nascimento:</strong>
    <%= atore.ano_nascimento %>
  </p>

  <p>
    <strong>Emaisl:</strong>
    <%= atore.emaisl %>
  </p>

</div>

app/views/atores/_form.html.erb
<%= form_with(model: atore) do |form| %>
  <% if atore.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(atore.errors.count, "error") %> prohibited this atore from being saved:</h2>

      <ul>
        <% atore.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :ano_nascimento, style: "display: block" %>
    <%= form.number_field :ano_nascimento %>
  </div>

  <div>
    <%= form.label :emaisl, style: "display: block" %>
    <%= form.text_field :emaisl %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/atores/edit.html.erb
<h1>Editing atore</h1>

<%= render "form", atore: @atore %>

<br>

<div>
  <%= link_to "Show this atore", @atore %> |
  <%= link_to "Back to atores", atores_path %>
</div>

app/views/atores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Atores</h1>

<div id="atores">
  <hr>
  <% @atores.each do |atore| %>
    <%= render atore %>
    <p>
      <%= link_to "Show this atore", atore %>
    </p>
    <hr>
  <% end %>
</div>

<%= link_to "New atore", new_atore_path %>

app/views/atores/new.html.erb
<h1>New atore</h1>

<%= render "form", atore: @atore %>

<br>

<div>
  <%= link_to "Back to atores", atores_path %>
</div>

app/views/atores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @atore %>


<div>
  <%= link_to "Edit this atore", edit_atore_path(@atore) %> |
  <%= link_to "Back to atores", atores_path %>

  <%= button_to "Destroy this atore", @atore, method: :delete %>
</div>