config/routes.rb
Rails.application.routes.draw do
  resources :logs, only: [:index]
  resources :comentarios
  resources :elencos
  resources :atores
  resources :filmes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "filmes#index"
end

app/models/elenco.rb
class Elenco < ApplicationRecord
  belongs_to :atore
  belongs_to :filme
end

app/controllers/elencos_controller.rb
class ElencosController < ApplicationController
  before_action :set_elenco, only: %i[ show edit update destroy ]

  # GET /elencos or /elencos.json
  def index
    @elencos = Elenco.all
  end

  # GET /elencos/1 or /elencos/1.json
  def show
  end

  # GET /elencos/new
  def new
    @elenco = Elenco.new
  end

  # GET /elencos/1/edit
  def edit
  end

  # POST /elencos or /elencos.json
  def create
    @elenco = Elenco.new(elenco_params)

    respond_to do |format|
      if @elenco.save
        format.html { redirect_to elenco_url(@elenco), notice: "Elenco was successfully created." }
        format.json { render :show, status: :created, location: @elenco }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @elenco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elencos/1 or /elencos/1.json
  def update
    respond_to do |format|
      if @elenco.update(elenco_params)
        format.html { redirect_to elenco_url(@elenco), notice: "Elenco was successfully updated." }
        format.json { render :show, status: :ok, location: @elenco }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @elenco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elencos/1 or /elencos/1.json
  def destroy
    @elenco.destroy

    respond_to do |format|
      format.html { redirect_to elencos_url, notice: "Elenco was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elenco
      @elenco = Elenco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def elenco_params
      params.require(:elenco).permit(:atore_id, :filme_id)
    end
end

app/helpers/elencos_helper.rb
module ElencosHelper
end

app/views/elencos/_elenco.html.erb
<div id="<%= dom_id elenco %>">
  <p>
    <strong>Atore:</strong>
    <%= elenco.atore_id %>
  </p>

  <p>
    <strong>Filme:</strong>
    <%= elenco.filme_id %>
  </p>

</div>

app/views/elencos/_form.html.erb
<%= form_with(model: elenco) do |form| %>
  <% if elenco.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(elenco.errors.count, "error") %> prohibited this elenco from being saved:</h2>

      <ul>
        <% elenco.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div>
      <%= form.label :atore_id, "Escolha um ator | atriz" %>
    </div>
    <%= form.collection_select :atore_id, Atore.order(:nome), :id, :nome %>
  </div>

  <br>

  <div>
    <div>
      <%= form.label :filme_id, "Escolha um filme" %>
    </div>
    <%= form.collection_select :filme_id, Filme.order(:nome), :id, :titulo %>
  </div>
  
  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/elencos/edit.html.erb
<h1>Editing elenco</h1>

<%= render "form", elenco: @elenco %>

<br>

<div>
  <%= link_to "Show this elenco", @elenco %> |
  <%= link_to "Back to elencos", elencos_path %>
</div>

app/views/elencos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Elencos</h1>

<div id="elencos">
  <hr>
  <% @elencos.each do |elenco| %>
    <%= render elenco %>
    <p>
      <%= link_to "Show this elenco", elenco %>
    </p>
    <hr>
  <% end %>
</div>

<%= link_to "New elenco", new_elenco_path %>

app/views/elencos/new.html.erb
<h1>Associar um ator ao elenco de um filme</h1>

<%= render "form", elenco: @elenco %>

<br>

<div>
  <%= link_to "Back to elencos", elencos_path %>
</div>

app/views/elencos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @elenco %>

<div>
  <%= link_to "Edit this elenco", edit_elenco_path(@elenco) %> |
  <%= link_to "Back to elencos", elencos_path %>

  <%= button_to "Destroy this elenco", @elenco, method: :delete %>
</div>