config/routes.rb
Rails.application.routes.draw do
  resources :logs, only: [:index]
  resources :comentarios
  resources :elencos
  resources :atores
  resources :filmes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "filmes#index"
end

app/models/filme.rb
class Filme < ApplicationRecord
    has_many :elencos
    has_many :comentarios
    has_many :atores, through: :elencos

    validates :titulo, :ano_lancamento, presence: true
    validates :titulo, uniqueness: true
end

app/controllers/filmes_controller.rb
class FilmesController < ApplicationController
  before_action :set_filme, only: %i[ show edit update destroy ]

  # GET /filmes or /filmes.json
  def index
    @filmes = Filme.all
  end

  # GET /filmes/1 or /filmes/1.json
  def show
    @elenco = @filme.elencos
    @comentarios = @filme.comentarios.aprovados
  end

  # GET /filmes/new
  def new
    @filme = Filme.new
  end

  # GET /filmes/1/edit
  def edit
  end

  # POST /filmes or /filmes.json
  def create
    @filme = Filme.new(filme_params)
    
    respond_to do |format|
      if @filme.save
        format.html { redirect_to filme_url(@filme), notice: "Filme was successfully created." }
        format.json { render :show, status: :created, location: @filme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filmes/1 or /filmes/1.json
  def update
    respond_to do |format|
      if @filme.update(filme_params)
        format.html { redirect_to filme_url(@filme), notice: "Filme was successfully updated." }
        format.json { render :show, status: :ok, location: @filme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filmes/1 or /filmes/1.json
  def destroy
    @filme.destroy

    respond_to do |format|
      format.html { redirect_to filmes_url, notice: "Filme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filme
      @filme = Filme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def filme_params
      params.require(:filme).permit(:titulo, :ano_lancamento)
    end
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/views/filmes/_filme.html.erb
<div id="<%= dom_id filme %>">
  <p>
    <strong>Titulo:</strong>
    <%= filme.titulo %>
  </p>

  <p>
    <strong>Ano lancamento:</strong>
    <%= filme.ano_lancamento %>
  </p>

</div>

app/views/filmes/_form.html.erb
<%= form_with(model: filme) do |form| %>
  <% if filme.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(filme.errors.count, "error") %> prohibited this filme from being saved:</h2>

      <ul>
        <% filme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :ano_lancamento, style: "display: block" %>
    <%= form.number_field :ano_lancamento %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/filmes/edit.html.erb
<h1>Editing filme</h1>

<%= render "form", filme: @filme %>

<br>

<div>
  <%= link_to "Show this filme", @filme %> |
  <%= link_to "Back to filmes", filmes_path %>
</div>

app/views/filmes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Filmes</h1>

<div id="filmes">
  <hr>
  <% @filmes.each do |filme| %>
    <%= render filme %>
    <p>
      <%= link_to "Show this filme", filme %>
    </p>

    <hr>
  <% end %>
</div>

<%= link_to "New filme", new_filme_path %>

app/views/filmes/new.html.erb
<h1>New filme</h1>

<%= render "form", filme: @filme %>

<br>

<div>
  <%= link_to "Back to filmes", filmes_path %>
</div>

app/views/filmes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @filme %>

<h4>ELENCO:</h4>
<ul>
  <% @elenco.each do |ator| %>
    <li>
      <%=  ator.atore.nome %>
    </li>
  <% end %>
</ul>

<h4>COMENTÁRIOS:</h4>
<ul>
  <% @comentarios.each do |comentario| %>
    <li>
      <%=  comentario.conteudo %>
    </li>
  <% end %>
</ul>

<div>
  <%= link_to "Edit this filme", edit_filme_path(@filme) %> |
  <%= link_to "Back to filmes", filmes_path %>

  <%= button_to "Destroy this filme", @filme, method: :delete %>
</div>